import type { ContentPost } from '@/lib/sihu-types';

/**
 * Seed / fallback content for the SIHU information hub. Mirrors what a live
 * Neon PostgreSQL database would hold; the store layer serves these published
 * posts when no DATABASE_URL is configured (dev / preview), matching the
 * graceful-degradation pattern used across this app.
 */
export const SIHU_SEED_POSTS: ContentPost[] = [
  {
    id: 'p1',
    slug: 'protecting-bamboo-seedlings-dry-season',
    title: 'Protecting Bamboo Seedlings in the Dry Season',
    summary: "Guardians share tips to keep bamboo alive in Kenya's dry spell: mulching, watering, and shading.",
    body: `Bamboo is one of the fastest-growing restoration species in Kenya, but the dry season is its toughest test. Guardians across Oloolua and the Rift Valley report losses concentrated in the first eight weeks after transplanting.

The three practices that show up most in CFA field notes are mulching, deep watering, and temporary shading. Mulching with dry grass or leaf litter around the base keeps soil moisture in place. Deep watering — a slow soak at the roots rather than a light sprinkle — pushes roots downward where the soil is cooler and wetter. Shade nets or inter-planting with a fast nurse crop buy seedlings the critical first season.

Verified planting data from connected CFA dashboards shows survival rates improve by roughly a third when all three are applied together. No single practice is a silver bullet; the combination is what matters.

Sources: CFA field journals (Oloolua), Kenya Forestry Research Institute (KEFRI) nursery guides. This article is human-authored and reviewed.`,
    contentType: 'FIELD_JOURNAL',
    category: 'CONSERVATION',
    language: 'EN',
    status: 'PUBLISHED',
    aiDisclosure: 'HUMAN',
    authorBadge: 'COMMUNITY_REPORTER',
    creatorName: 'Grace Wangari',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['Bamboo', 'Restoration', 'Dry Season'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: null,
    featured: false,
    viewsCount: 341,
    likesCount: 47,
    tipsEarnedKes: 1200,
    aiReport: null,
    editorNote: 'Approved after verification of KEFRI references.',
    reviewedAt: '2026-08-27T09:00:00.000Z',
    publishedAt: '2026-08-28T08:00:00.000Z',
    createdAt: '2026-08-24T10:00:00.000Z',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 'p2',
    slug: 'jaza-miti-explained',
    title: 'Jaza Miti: What It Is and How Your CFA Can Join',
    summary: 'Jaza Miti turns verified tree planting into traceable conservation records. Here is how the methodology works in practice.',
    body: `Jaza Miti is a community tree-planting methodology that records verification for every tree a CFA plants. Each tree is logged against a structured record: species, nursery source, planting date, zone, and the guardian who planted it. Records are organized, annotated, and consistency-checked with AI assistance, then reviewed by a human verifier before anything is anchored on-chain.

For a CFA, joining means its nursery inventory and planting records in its own operational dashboard can feed the Jaza Miti pipeline. The Information Hub never reaches into CFA dashboards automatically — permission gates decide what is shared upward for verification.

Economic value comes later: verified records become the inputs for conservation finance, carbon accounting, and eventual tokenized representations on Avalanche. This article is AI-assisted: the methodology structure was drafted with AI, then confirmed against Jaza Miti documentation and CFA verification records by an editor.`,
    contentType: 'EDUCATIONAL_GUIDE',
    category: 'CONSERVATION',
    language: 'EN',
    status: 'PUBLISHED',
    aiDisclosure: 'AI_ASSISTED',
    authorBadge: 'CONSERVATION_EXPERT',
    creatorName: 'Joseph Kimani',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['JazaMiti', 'Verification', 'Methodology'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: null,
    featured: true,
    viewsCount: 512,
    likesCount: 89,
    tipsEarnedKes: 2400,
    aiReport: null,
    editorNote: 'AI-assisted disclosure applied per editorial policy.',
    reviewedAt: '2026-08-26T14:00:00.000Z',
    publishedAt: '2026-08-27T07:30:00.000Z',
    createdAt: '2026-08-22T09:00:00.000Z',
    updatedAt: '2026-08-27T07:30:00.000Z',
  },
  {
    id: 'p3',
    slug: 'mau-forest-cfa-carbon-credits-avalanche',
    title: 'Mau Forest CFA Bases 8,420 Carbon Credits on Avalanche',
    summary: 'Patrol logs verified and anchored on-chain. A concrete example of verifiable conservation impact.',
    body: `A Mau Forest CFA turned 18 months of patrol logs and planting records into 8,420 verified carbon credits. The workflow matched the hub's verification path: conservation activity captured in the CFA dashboard → structured record → evidence (photos, GPS, logs) → human verification → records anchored on Avalanche as verification proofs.

Importantly, the ledger of anchors holds hashes and provenance — not the underlying forest data, which stays off-chain. This is the selective anchoring model: ordinary browsing, likes, and reads stay off-chain; verification proofs are what get anchored.

The CFA's own dashboard remains the source of operational truth. The Information Hub and its blockchain layer organize, verify, and make that work traceable — they do not replace the people doing it. AI-assisted article; figures verified against the on-chain anchor log by an editor.`,
    contentType: 'ARTICLE',
    category: 'CLIMATE',
    language: 'EN',
    status: 'PUBLISHED',
    aiDisclosure: 'AI_ASSISTED',
    authorBadge: 'COMMUNITY_REPORTER',
    creatorName: 'Agnes Chebet',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['Carbon', 'Avalanche', 'Verification'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: null,
    featured: false,
    viewsCount: 617,
    likesCount: 98,
    tipsEarnedKes: 2800,
    aiReport: null,
    editorNote: null,
    reviewedAt: '2026-08-21T16:00:00.000Z',
    publishedAt: '2026-08-22T07:00:00.000Z',
    createdAt: '2026-08-18T11:00:00.000Z',
    updatedAt: '2026-08-22T07:00:00.000Z',
  },
  {
    id: 'p4',
    slug: 'gtci-green-tree-commodities-guide',
    title: 'Green Tree Commodities Initiative (GTCI): A Guardian Field Guide',
    summary: 'How the Green Tree Commodities approach links nursery care to real commodity value for tree-owning households.',
    body: `The Green Tree Commodities Initiative (GTCI) treats the tree itself as a commodity with a lifecycle: nursery, planting, growth, harvest, and market. Where plantation models think in hectares, GTCI thinks in individual trees owned by households and aggregated through CFAs and co-ops.

Households register their trees, receive growing guidance through the nursery and early years, and later connect to aggregated markets. The data GTCI collects — species, age, survival, harvest — is exactly the sort of structured record the Conservation hub can verify and, later, represent as traceable digital assets.

This article is a general introduction and does not claim a partnership with GTCI beyond describing the methodology as it is publicly documented. Human-authored.`,
    contentType: 'ARTICLE',
    category: 'CONSERVATION',
    language: 'EN',
    status: 'PUBLISHED',
    aiDisclosure: 'HUMAN',
    authorBadge: 'CONSERVATION_EXPERT',
    creatorName: 'Beatrice Mutua',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['GTCI', 'Commodities', 'Trees'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: null,
    featured: false,
    viewsCount: 403,
    likesCount: 62,
    tipsEarnedKes: 1800,
    aiReport: null,
    editorNote: null,
    reviewedAt: '2026-08-20T09:00:00.000Z',
    publishedAt: '2026-08-21T08:00:00.000Z',
    createdAt: '2026-08-16T10:00:00.000Z',
    updatedAt: '2026-08-21T08:00:00.000Z',
  },
  {
    id: 'p5',
    slug: 'nursery-stock-rule-of-square',
    title: 'The Rule of Square: Nursery Stock, Spacing, and Water',
    summary: 'A short practical guide to tree nursery practices every new guardian should know.',
    body: `The "rule of square" is shorthand for what KEFRI nursery guides keep repeating: healthy nursery stock means the right species for the site, correct spacing at planting, and water managed through the first two seasons.

Spacing matters more than people expect. Seedlings planted too densely compete for the same shallow water; too sparsely, you waste scarce shade. Measuring a square meter per sapling for most timber species, and adjusting for pioneer species that prefer closer company, is a workable starting point.

This guide synthesizes KEFRI training materials and CFA field notes. Human-authored; reviewed by a hub editor.`,
    contentType: 'EDUCATIONAL_GUIDE',
    category: 'CONSERVATION',
    language: 'EN',
    status: 'PUBLISHED',
    aiDisclosure: 'HUMAN',
    authorBadge: 'AGRI_EXPERT',
    creatorName: 'Daniel Ruto',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['Nursery', 'Spacing', 'Water'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: null,
    featured: false,
    viewsCount: 290,
    likesCount: 54,
    tipsEarnedKes: 1500,
    aiReport: null,
    editorNote: null,
    reviewedAt: '2026-08-19T11:00:00.000Z',
    publishedAt: '2026-08-20T07:00:00.000Z',
    createdAt: '2026-08-14T09:00:00.000Z',
    updatedAt: '2026-08-20T07:00:00.000Z',
  },
  {
    id: 'p6',
    slug: 'kai-smart-ledger-voice-guide',
    title: 'KAI Smart Ledger: Voice Guide for Traders',
    summary: 'Record daily sales, credit, and stock by voice. No internet needed.',
    body: `MSME owners tell the same story: bookkeeping collapses when business is busy. The KAI Smart Ledger lets a trader record sales, credit given, and stock movement by speaking, so entries happen in the moment they happen.

Entries stream into an intelligent ledger that separates income, expense, credit, and debt — and gives plain-language advice on cash flow. Ledger data lives in structured records that a business owner controls; nothing is shared without permission. Audio episode (Swahili/English).`,
    contentType: 'AUDIO_PODCAST',
    category: 'MSME_GROWTH',
    language: 'SW',
    status: 'PUBLISHED',
    aiDisclosure: 'HUMAN',
    authorBadge: 'AGRI_EXPERT',
    creatorName: 'Fatuma Hassan',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['Ledger', 'Voice', 'MSME'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: 482,
    featured: false,
    viewsCount: 215,
    likesCount: 38,
    tipsEarnedKes: 900,
    aiReport: null,
    editorNote: null,
    reviewedAt: '2026-08-18T10:00:00.000Z',
    publishedAt: '2026-08-19T08:00:00.000Z',
    createdAt: '2026-08-12T12:00:00.000Z',
    updatedAt: '2026-08-19T08:00:00.000Z',
  },
  {
    id: 'p7',
    slug: 'survey-farmers-want-conservation-finance',
    title: 'On the Ground: What Farmers Asked Us About Conservation Finance',
    summary: 'Field survey highlights from five counties — and what they mean for the hub.',
    body: `Over six weeks we asked farmers and CFA members in five counties what they hoped conservation finance would actually do. Three answers came back consistently: payouts timed to the season, value they can verify themselves, and markets they can reach without a middleman controlling the price.

The hub is designed around those three answers. Education content explains the terms. Methodology pages show exactly what data a record requires before it can be verified for finance. Nothing is promised on-chain that a guardian cannot check. Human-authored.`,
    contentType: 'REPORT',
    category: 'COMMUNITY',
    language: 'EN',
    status: 'PUBLISHED',
    aiDisclosure: 'HUMAN',
    authorBadge: 'COMMUNITY_REPORTER',
    creatorName: 'Akinyi Odhiambo',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['Survey', 'Finance', 'Community'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: null,
    featured: false,
    viewsCount: 189,
    likesCount: 29,
    tipsEarnedKes: 700,
    aiReport: null,
    editorNote: null,
    reviewedAt: '2026-08-17T09:00:00.000Z',
    publishedAt: '2026-08-18T07:00:00.000Z',
    createdAt: '2026-08-10T08:00:00.000Z',
    updatedAt: '2026-08-18T07:00:00.000Z',
  },
  {
    id: 'p8',
    slug: 'what-to-plant-where-conservation-trees',
    title: 'What to Plant Where: A Conservation Tree Species Primer',
    summary: 'A plain-language guide to matching species to site — soil, rainfall, and purpose.',
    body: `Matching species to site is the difference between a tree that thrives and a nursery batch that burns through water all season. The primer groups species by purpose: riverine stabilizers, dryland reforesters, timber species, and bee pasture.

For each, it records the rainfall range, soil preference, spacing, and the survival notes observed in CFA plantings. Pairs with the hub's tree species reference under Conservation Knowledge. AI-assisted draft, editor-reviewed against KEFRI species data.`,
    contentType: 'EDUCATIONAL_GUIDE',
    category: 'CONSERVATION',
    language: 'EN',
    status: 'PUBLISHED',
    aiDisclosure: 'AI_ASSISTED',
    authorBadge: 'AGRI_EXPERT',
    creatorName: 'Wanjiru Kamau',
    creatorUserId: null,
    creatorEmail: null,
    tags: ['Species', 'Planting', 'Restoration'],
    mediaUrl: null,
    audioUrl: null,
    audioDurationSeconds: null,
    featured: false,
    viewsCount: 347,
    likesCount: 51,
    tipsEarnedKes: 1100,
    aiReport: null,
    editorNote: null,
    reviewedAt: '2026-08-16T14:00:00.000Z',
    publishedAt: '2026-08-17T07:00:00.000Z',
    createdAt: '2026-08-11T09:00:00.000Z',
    updatedAt: '2026-08-17T07:00:00.000Z',
  },
];